name: Bazzite-Style Gamescope Build

on:
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: registry.fedoraproject.org/fedora:43

    steps:
      - name: Install Official BuildRequires
        run: |
          # referring to https://github.com/ublue-os/bazzite/blob/main/spec_files/gamescope/gamescope.spec
          dnf install -y git meson ninja-build gcc-c++ pkgconf-pkg-config cmake \
          wayland-devel wayland-protocols-devel libX11-devel libXcomposite-devel \
          libXcursor-devel libXdamage-devel libXext-devel libXfixes-devel \
          libXi-devel libXinerama-devel libXrandr-devel libXrender-devel \
          libXres-devel libXv-devel libXxf86vm-devel libdrm-devel libinput-devel \
          libxkbcommon-devel pixman-devel mesa-libgbm-devel mesa-libEGL-devel \
          mesa-libGLES-devel vulkan-loader-devel libseat-devel hwdata-devel \
          libavif-devel libcap-devel systemd-devel libcap-ng-devel \
          libdisplay-info-devel google-benchmark-devel glslang libliftoff-devel \
          stb_image-devel stb_image_write-devel stb_image_resize-devel \
          pipewire-devel pulseaudio-libs-devel glm-devel libXmu-devel edid-decode

      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: feat-touchpad-support
          fetch-depth: 0
          submodules: recursive

      - name: Sync Upstream
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git remote add upstream https://github.com/bazzite-org/gamescope.git
          git fetch upstream gamescope-ba
          git merge upstream/gamescope-ba --no-edit || (echo "Conflict!" && exit 1)
          git push origin feat-touchpad-support

      - name: Meson Configure (Following Spec Flags)
        run: |
          # referring to https://github.com/ublue-os/bazzite/blob/main/spec_files/gamescope/gamescope.spec
          meson setup build/ \
            --buildtype=release \
            -Dpipewire=enabled \
            -Davif=enabled \
            -Drt_priority=enabled \
            -Dinput_emulation=true \
            -Dvideobridge=false \
            -Dprefer_vk_device=AMD

      - name: Ninja Build
        run: ninja -C build/

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: gamescope-bazzite-fc43
          path: build/gamescope
